### ISSUE TITLE
minimize() causing error because of implementation of sub project

### ISSUE THREAD

**Issue by Juli0q** [GradleUp/shadow#1004]
### Expected and Results

Minimize breaks when trying to use implementation with a sub project.

`Cannot read field "forJava" because "parsedFileName" is null`

### Related environent and versions

Gradle 8.9
Shadow 8.3.3
Fedora 39

### Reproduction steps

1. Create a Gradle project with multiple sub projects
2. Try to use `implementation` to implement a sub project into a sub project
3. Try to build a shadowJar

**Comment by Goooler** [comment]
I tried, this works for Ktlint after adding `minimize()`

https://github.com/pinterest/ktlint/blob/50e44a7d11207a96577fedd059cb95ffa225aa17/ktlint-cli/build.gradle.kts#L17-L27

**Comment by Juli0q** [comment]
Okay I will try to create an example repo. 

I am using a different syntax for implementing the sub project, does that make a difference?
`implementation(project(":MySubProject"))`

**Comment by Goooler** [comment]
Nope.

**Comment by Juli0q** [comment]
I can't replicate the issue in a separate project either. I will look into why my project has this issue later today.

**Comment by Juli0q** [comment]
I managed to fix the issue. I had the buildSrc folder generated by gradle init which caused problems with the plugins I used.
