### ISSUE TITLE
shadow jar with > 65535 files fails

### ISSUE THREAD

**Issue by pkallos** [GradleUp/shadow#107]
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':xxxxx:shadowJar'.
> org.apache.tools.zip.Zip64RequiredException: archive contains more than 65535 entries.

  To build this archive, please enable the zip64 extension.
  See: http://gradle.org/docs/2.1/dsl/org.gradle.api.tasks.bundling.Zip.html#org.gradle.api.tasks.bundling.Zip:zip64

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by balldarrens** [comment]
I am seeing the following error:
java.util.zip.ZipException: central directory zip64 extended information extra field's length doesn't match central directory data.  Expected length 0 but is 16

Not sure how to solve this.  Any help would be appreciated.

**Comment by johnrengelman** [comment]
Have you set the above property?

**Comment by balldarrens** [comment]
Yes, it is set.

This is my build file:
apply plugin: 'java'
apply plugin: 'idea'
apply plugin: 'com.github.johnrengelman.shadow'

ext.webProject=false

description = "Uber Testing Jar"
def releaseNumber = System.getProperty("releaseNumber", "SNAPSHOT")
version = "${rootProject.ext.releasePrefix}1.0-${releaseNumber}"

buildscript {
	repositories {
		jcenter()
	}
	dependencies {
		classpath 'com.github.jengelman.gradle.plugins:shadow:1.2.1'
	}
}


dependencies {
	compile project(':common'),
			project(':core'),
			project(':apiService')

	compile 'org.apache.jmeter:ApacheJMeter:2.11'
	compile 'org.apache.jmeter:ApacheJMeter_java:2.11'

	testCompile project(':common').sourceSets.test.output,
			project(':core').sourceSets.test.output,
			project(':apiService').sourceSets.test.output
}

jar {
	manifest {
		attributes(
				"Manifest-Version" : "1.0",
		)
	}
}

shadowJar {
	zip64 true
	mergeServiceFiles()
	exclude "META-INF/*.SF"
	exclude 'META-INF/*.DSA'
	exclude 'META-INF/*.RSA'
	exclude "LICENSE*"
}

**Comment by johnrengelman** [comment]
Please open a new ticket with this info.

**Comment by balldarrens** [comment]
Could this be a jarsigner issue - the environment is using jdk8 and possibly the jars are signed using < 1.6?  The digest algorithm has been changed to SHA-256 from SHA1withDSA.  I am not sure - just digging around to see this error and there is not a lot of info.

**Comment by balldarrens** [comment]
New issue is created.  https://github.com/johnrengelman/shadow/issues/128

**Comment by mjduijn** [comment]
For anyone using the Gradle Kotlin-DSL, the above answers result in the following:
```kotlin
import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar<br/>

...

tasks {  
    "shadowJar"(ShadowJar::class) {  
        isZip64 = true  
    }  
}
```

**Comment by gildor** [comment]
for Kotlin DSL, if you applied `shadow` using `plugins` block now you can use static accessor instead:

```
plugins {
   id("com.github.johnrengelman.shadow") version shadowVersion
}
tasks.shadowJar {
   isZip64 = true  
}
```

**Comment by drouck** [comment]
if you followed this tutorial:
https://www.artificialworlds.net/blog/2019/07/12/building-an-all-in-one-jar-in-gradle-with-the-kotlin-dsl/

you can add setZip64(true) to this section:

tasks.withType<ShadowJar>() {
    setZip64(true)
    manifest {
        attributes["Main-Class"] = "HelloKt"
    }
}

**Comment by seunggabi** [comment]
### my case 
```kotlin
withType<Jar> {
    enabled = true
    isZip64 = true
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    archiveFileName.set("$project.jar")

    from(
        configurations.compileClasspath.map { config ->
            config.map {
                if (it.isDirectory) {
                    it
                } else {
                    zipTree(it)
                }
            }
        }
    )
}
```
