### ISSUE TITLE
Creating a custom shadow jar task results in errors 

### ISSUE THREAD

**Issue by FlorianMichael** [GradleUp/shadow#1070]
### Expected and Results

I have added a custom shadow jar task in my project looking like this:
``` java
task buildBetaJar(type: com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar) {
    // Shadow jar without exclusions above (for beta)
    archiveFileName.set("AugustusBeta.jar")
    from(sourceSets.main.output)
    configurations = [project.configurations.runtimeClasspath]
}
```
When using shadow `9.0.0+` and compiling I get this error:
<img width="731" alt="image" src="https://github.com/user-attachments/assets/f56307de-0e68-473b-bd3f-e549cd0097f8">

After looking at the git commits this seems to be related to #1044, although I'm unsure if this is intended behaviour since `ShadowJar` still should have default values and not force the user to have all properties set?

### Related environent and versions

- Gradle 8.11.1
- shadow 9.0.0-beta2

### Reproduction steps

1. Create a Gradle project with the latest beta shadow build
2. Copy in the custom task above and try to run `gradle build`
3. Get the error shown above

**Comment by Goooler** [comment]
Oh, yes, you are using a custom ShadowJar task, properties are now initialized like 

https://github.com/GradleUp/shadow/blob/8ddb7c5334d15ef054f37aa9999e7680a55c5b2a/src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowJavaPlugin.kt#L94-L99

**Comment by FlorianMichael** [comment]
Thank you for fixing it :) We really appreciate your work on maintaining shadow

**Comment by Goooler** [comment]
My pleasure. Thanks for your report!

**Comment by rjaros** [comment]
Can I create custom shadow jar task without `DefaultDependencyFilter` class, which is internal?

**Comment by FlorianMichael** [comment]
This should be possible with the code I provided above

**Comment by rjaros** [comment]
I think I should wait till this fix is released (beta3?)

**Comment by FlorianMichael** [comment]
Yeah
