### ISSUE TITLE
SoftwareComponent not found

### ISSUE THREAD

**Issue by DuoDuoJuZi** [GradleUp/shadow#1119]
### Expected and Results

When using,can publish a normal jar into the package through shadowJar

### Related environent and versions

used github action and github packages

### Reproduction steps

1. I tried using the github package's dependencies.I then discovered that the jar released by the github package was empty (only META-INF)
2. I thought the problem was with `from(components["java"])`, so I changed it to `from(components["shadow"])`
3. When the github workflow runs, everything is fine until publish to gitHub packages, it reports the error `SoftwareComponent with name 'shadow' not found`

### Anything else?

The last GitHub Action [here](https://github.com/LegacyLands/legacy-lands-library/actions/runs/12493619944/job/34862271072)
The Gradle Kotlin DSL Build Script [here](https://github.com/LegacyLands/legacy-lands-library/blob/main/build.gradle.kts)
I have tried many different approaches....

**Comment by Goooler** [comment]
You get Shadow component from the rootproject but Shadow plugin has not been applied to the root.

**Comment by DuoDuoJuZi** [comment]
> You get Shadow component from the rootproject but Shadow plugin has not been applied to the root.

Uh, so I should apply the shadow plugin to `allprojects`? Or use `artifact(tasks.named<ShadowJar>("shadowJar").get().archiveFile.get())`?

**Comment by Goooler** [comment]
That's your business not this plugin.
