### ISSUE TITLE
transformer fails with "Could not find property"

### ISSUE THREAD

**Issue by JohnLCaron** [GradleUp/shadow#15]
probably a newbee question:

the build file:

build.gradle:

```
buildscript {
    repositories {
        maven {
            name 'Gradle Shadow'
            url 'http://dl.bintray.com/content/johnrengelman/gradle-plugins'
        }
    }
    dependencies {
        classpath 'org.gradle.plugins:shadow:0.7.4'
    }
}

apply plugin: 'shadow'

dependencies {
  compile project(':cdm')
  compile project(':grib')
  compile project(':tdcommon')
  compile 'log4j:log4j:1.2.17'
  runtime 'org.slf4j:slf4j-log4j12:1.7.5'
  compile ('org.springframework:spring-core:3.1.1.RELEASE')
  compile ('org.springframework:spring-context:3.1.1.RELEASE')
  compile ('org.springframework:spring-beans:3.1.1.RELEASE')
}


ext {
  tdmJar = 'tdm-'+version+'.jar'
}

shadow {
   transformer(org.gradle.api.plugins.shadow.transformers.AppendingTransfomer) {
      resource = 'META-INF/spring.handlers'
   }
   transformer(org.gradle.api.plugins.shadow.transformers.AppendingTransfomer) {
      resource = 'META-INF/spring.schemas'
   }
}
```
# 

the output:

$ gradle clean shadow -x test -p tdm
The TaskContainer.add() method has been deprecated and is scheduled to be removed in Gradle 2.0. Please use the create() method instead.

FAILURE: Build failed with an exception.
- Where:
  Build file 'C:\dev\github\thredds\tdm\build.gradle' line: 32
- What went wrong:
  A problem occurred evaluating project ':tdm'.
  
  > Could not find property 'org' on org.gradle.api.plugins.shadow.ShadowTaskExtension_Decorated@59f0780c.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 9.52 secs

caron@ROBERTO /c/dev/github/thredds (target-4.4.0)
$ which gradle
/c/dev/gradle-1.6/bin/gradle

caron@ROBERTO /c/dev/github/thredds (target-4.4.0)

**Comment by flow-de-cologne** [comment]
Old post but... you're missing the 's' in Transfomer.

**Comment by JohnLCaron** [comment]
thanks
