### ISSUE TITLE
Package only certain dependencies.

### ISSUE THREAD

**Issue by tlaundal** [GradleUp/shadow#31]
I have a project with a costom gradle plugin that adds a lot of dependencies. I have one additional dependency, which again have one dependency, which I need to include in my jar. The two dependencies have different groupId's so I couldn't find a way using `groupFilter`. I also tried using `exclude` and `include`, but I couldn't figure out how to exclude everything, and then include certain folders.

(I know this might not be an _issue_, but this was the best place I found to ask)

**Comment by bikrant** [comment]
I think you can simply do:
shadowJar {
    dependencies {
        include(dependency('commons-cli:commons-cli'))
        include(dependency('com.googlecode.json-simple:json-simple'))
    }
}

If I'm not mistaken, that should include just two jars.

**Comment by a-k-g** [comment]
:+1: for this FR. Is it possible in the current versions?

**Comment by a-k-g** [comment]
Just figured out the way to do this in the current versions. Say you have-

```
dependencies {
   compile 'jackson:some-module:1.0'
   compile 'guava:some-other-module:1.0'
}
```

and you only want the fat jar to include a shaded `jackson` and not `guava`, you could do-

```
shadowJar {
   dependencies {
      include(dependency('jackson:some-module:1.0'))
   }
   relocate "com.jackson", "shaded.com.jackson"
}
```

**Comment by KhogaEslam** [comment]
```
configurations {
    provided
    compile.extendsFrom provided
}

dependencies {
    provided 'WHATEVER' // Packages you don't need to add to jar
    provided 'Other WHATEVER' // Packages you don't need to add to jar

    shadow 'OTHER' // Packages you need to add to jar
    shadow 'Another OTHER' // Packages you need to add to jar
}

shadowJar {
    configurations = [project.configurations.shadow] // ***
}
```

as mentioned [here](https://imperceptiblethoughts.com/shadow/configuration/dependencies/) 

line *** is the way to tell shadow what dependencies to include in jar

**Comment by aiqency** [comment]
Kotlin DSL version of @KhogaEslam solution:

```koltin
tasks {
    build {
        dependsOn(shadowJar)
    }

    named<ShadowJar>("shadowJar") {
        configurations = mutableListOf(project.configurations.shadow.get())
    }
}

dependencies {
    implementation("...") // excluded
    shadow("...") // included
}
```

Maybe it can save someone's time.

**Comment by pietelite** [comment]
> Kotlin DSL version of @KhogaEslam solution:
> 
> ```
> tasks {
>     build {
>         dependsOn(shadowJar)
>     }
> 
>     named<ShadowJar>("shadowJar") {
>         configurations = listOf(project.configurations.shadow.get())
>     }
> }
> 
> dependencies {
>     implementation("...") // excluded
>     shadow("...") // included
> }
> ```
> 
> Maybe it can save someone's time.

I thought it was the other way around. 

> Dependencies added to the shadow configuration are not bundled into the output JAR. 

https://imperceptiblethoughts.com/shadow/configuration/#configuring-the-runtime-classpath
