### ISSUE TITLE
How to use shadow jar as main project artifact?

### ISSUE THREAD

**Issue by rburgst** [GradleUp/shadow#34]
Hi

I am not sure how I would declare the shaded jar as my main output artifact so that other projects (using dependency compile project(":shaded")) use this jar rather than the normal jar.

I saw that 
"Automatically configure Shadow output as publish artifact"

is on the road map, however, I was wondering whether there is something that I can do manually right now to get this to work?

**Comment by mcandre** [comment]
On my machine, gradle complains that the shadowJar task does not have an `outputJar` property. Was it renamed?

**Comment by johnrengelman** [comment]
Yes...`ShadowJarTask` extends from the Gradle `Jar` so you would just reference the task the same way you would a `Jar` task.

**Comment by mohamnag** [comment]
I have actually a similar problem and tried the following in build file:
```
artifacts {
    archives(shadowJar.outputJar) {
        builtBy shadowJar
    }
}
```
using the most recent version of the plugin I get the following error:
```
 Could not get unknown property 'outputJar' for task ':shadowJar' of type com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar.
```

PS: I'm actually trying to publish the shadowJar alongside the normal JAR.

**Comment by johnrengelman** [comment]
The code above is 2 years old and since then shadow was refactor to more closely resemble a standard jar task. Please look at the Gradle docs for the Jar task to see th correct property name. Or look at the User Guide which is linked to in the readme for this project. There are ezamoles of configuring publishing in there.

**Comment by mohamnag** [comment]
Ok, I did the following:
```
artifacts {
    archives sourcesJar
    archives javadocJar
    archives shadowJar
}
```
but now I get the following error:
```
Could not transfer artifact com.group:name:jar:shadow-classifier:1.0-20160725.192618-22 from/to remote (http://mym2.reop/repository/maven-snapshots): Broken pipe
```

**Comment by johnrengelman** [comment]
You're gonna have to dig into it. The examples in the User Guide are part of test cases a verified. Anything beyond that is beyond my control.
If you find a specific issue or are able to create a new, minimal project that exhibits this problem, please open a new ticket.
