### ISSUE TITLE
Include shadow JAR of another submodule instead of just compile output.

### ISSUE THREAD

**Issue by MineDev2014** [GradleUp/shadow#44]
I have a project with a similar project layout as in the build scripts here: https://gist.github.com/MineDev2014/4816b9ee78e0c5e1cf26

The project has multiple submodules, the core module includes some libraries and relocates them. Now I want to create another module that will just extend the core module so include the content of the shadow JAR of it's dependencies. I want to switch from Maven (with the shade plugin) to Gradle and it was working with Maven before.

But when using Gradle the shadow JAR of the Core module contains the correct relocated library but the other module does just include the original library without the relocation. Is it possible to include the shadow JAR of the other module instead?

**Comment by JLLeitschuh** [comment]
This worked for me with gradle 2.6
```
    shadowJar {
        artifacts {
            shadow(tasks.shadowJar.archivePath) {
                builtBy shadowJar
            }
        }
    }
```

**Comment by krmahadevan** [comment]
@johnrengelman - I figured this out. Adding the details here, in-case anyone is looking for ways of getting through with this.

Here's the blog that made it clear : https://medium.com/@akhaku/java-class-shadowing-and-shading-9439b0eacb13

The build file for `m1/build.gradle`

```
import com.github.jengelman.gradle.plugins.shadow.tasks.ConfigureShadowRelocation

plugins {
    id 'java-library'
    id 'com.github.johnrengelman.shadow' version '7.1.0'
}

dependencies {
    implementation 'org.assertj:assertj-core:3.21.0'
}

task relocateShadowJar(type: ConfigureShadowRelocation) {
    target = tasks.shadowJar
    prefix = 'rationale.emotions'
}

shadowJar {
    dependsOn(relocateShadowJar)
}
```

And here's the `m2/build.gradle` which consumes the shaded dependency from `m1`

```
plugins {
    id 'java-library'
}

dependencies {
    implementation project(path: ':m1', configuration: 'shadow')
    implementation 'org.testng:testng:7.4.0'
}
```
