### ISSUE TITLE
Java 21 Support

### ISSUE THREAD

**Issue by Desoroxxx** [GradleUp/shadow#888]
### Shadow Version
8.1.1
### Gradle Version
8.4-rc-3
### Expected Behavior
Work
### Actual Behavior
https://mclo.gs/lePWlta

**Comment by Goooler** [comment]
This will be fixed by #879 or #876.

**Comment by Goooler** [comment]
You can try my fork, see https://github.com/johnrengelman/shadow/pull/876#issuecomment-1783983216.
