### ISSUE TITLE
Use new file permission API from Gradle 8.3

### ISSUE THREAD

**Issue by jbartok** [GradleUp/shadow#892]
Gradle 8.3 introduces a [new API for setting file permissions](https://docs.gradle.org/8.3/userguide/working_with_files.html#sec:setting_file_permissions).

We intend to deprecate the old, Unix mode based API in Gradle, but we can't do that until major Gradle plugins don't start using the new one.

For that reason would be good to upgrade this plugin to use Gradle 8.3 and switch internal code to the new API.

**Comment by Goooler** [comment]
I'd addressed the fix to #876, can you take a look?
