### ISSUE TITLE
Future home/support for Shadow?

### ISSUE THREAD

**Issue by johnrengelman** [GradleUp/shadow#908]
This project started 12 years ago (https://github.com/johnrengelman/shadow/commit/eb773b14cc47154291bbfe9e40be5f56c7d54824) as a way for me to address CI/CD tooling for developer teams when I was consulting. It has had a long run and I'm glad that the community has enjoyed the capabilities that it brings.
But as many of you have noticed, I have not had as much time to manage this project over the last few years. There's a few big points that I'd like to call out:

* I believe that shadow is _feature complete_ and any additional capabilities should be added as extensions or wrappers to Shadow. I could see some future development to make Shadow more generic with plugins to enable this, but IMO, shadow shouldn't be bloated with a bunch of different features.
* Shadows place in the ecosystem is directly impacted by the more rapid development and releases in both Java and Gradle and so this project has become mostly responding to those changes...particularly Gradle changes since Shadow relies on some internal APIs of Gradle.
* There is an opportunity to influence the Gradle team to expose more public API or structures that would make Shadow simpler, but that will require some significant time investment to work through their processes.
* Over the last decade my career trajectory has changed sufficiently that I can't reasonably argue that working on Shadow is related to my job, so that puts it has a night/weekend hobby where I'd prefer to dedicate more time to my family.

With all that said, it's time for Shadow to find either a new home or a new set of maintainers that I can turn the keys over to. @Goooler has been doing a wonderful job lately and is supporting users with their fork. I see a few options that are viable:

1. Keep the plugin here and add additional maintainers that can commit and release
2. Move to @Goooler's fork and deprecate this plugin
3. Identify a foundation/community model that would take the plugin with multiple maintainers (I bring this up in case there is strong feeling to get individual's names out of the plugin id).

Please feel free to share your thoughts. I'd like to get a consensus and make a decision soon.

**Comment by staktrace** [comment]
Thank you for all the work you've put into this project over the years! I don't have strong feelings but I also prefer option 3 if that's viable. At least at [CashApp](https://github.com/cashapp/) we use this project widely in our internal builds and plan to continue to do so with newer versions of Gradle. As long as I'm working in my current capacity I'm happy to try to contribute fixes and patches that serve that goal.

**Comment by oleg-nenashev** [comment]
Hello. @johnrengelman. From my side (Gradle community manager), I am interested in building a community hub and community-governed GitHub organization that would offer a home for plugin and other key components maintainers who want to ensure continuity of the plugins. I call it _Project Gradliverse_ (inspired by Quarkus), but this is not a finalized name.

From GitHub perspective it would be an org that offers hosting, various automations to simplify the life of maintainers (CI/CD, release flow, changelogs, docs hosting, etc.), encourages the best practices for plugin development, and also clear governance model that offers the maintainers almost full powers but defines a process of transition should the maintainer want to move one or become inactive. It is somehow aligned with how [Jenkins governance](https://www.jenkins.io/project/governance) is defined and how we support maintainers

I have not yet published the proposal, but I am discussing it with the community members. I hope to go live soon, and I think the Shadow Plugin could be one of the pilot projects moving there

**Comment by oleg-nenashev** [comment]
Hi @jimshowalter @Goooler @martinbonnin

While I finalize the https://github.com/gradle/community/issues/15 proposal and the approvals, I would suggest the following temporary solution:

1. We transfer the repository to https://github.com/GradleUp, one of the popular GitHub organizations hosting a number of Gradle tools. I confirmed with @martinbonnin that he is open to it. CC @deepy too
2.  We synchronize changes by @Goooler to the new upstream, and I guess he becomes a maintainer of the repository
3. Until https://github.com/gradle/community/issues/15 is finalized, we do not change artifact/group IDs, but then we do something about it to unify for such a community hub recommendations we define

WDYT?

**Comment by johnrengelman** [comment]
@oleg-nenashev The general outline above sounds promising. I think moving to https://github.com/GradleUp has a middle ground might be unnecessary though. I could add @Goooler as a collaborator to this repository and to the circle ci project and I believe you all could add portal access for him to publish plugin versions?

**Comment by oleg-nenashev** [comment]
> I could add @Goooler as a collaborator to this repository and to the circle ci project and I believe you all could add portal access for him to publish plugin versions?

Yes, this is possible.

**Comment by kennytv** [comment]
I strongly believe that moving this project to some kind of organization with at least one other admin (whether one created by you or someone else) is necessary to avoid running into the same issue again. Having only a single person with administrative permissions on such a widely used tool is the most common factor for the entire project disappearing or breaking up into vaguely promoted forks

At the same time and with the same line of thought, I agree with jimshowalter that I would like to see features like relocation and easy exclusion/inclusion in Gradle-proper, or at least in an officially supported plugin. A community hub for gradle plugins would be the next best thing to that, as long as the bus factor doesn't stay at one or below

**Comment by oleg-nenashev** [comment]
I'm finishing the proposal for Gradliverse, so it should move forward in a few weeks. I will be happy to publicize the version once I have a first review and green light.

@Goooler in the meantime, do you need any help from me to do the next release with your changes?

**Comment by Goooler** [comment]
Yes, please.

**Comment by gtach2o** [comment]
Hello,
any update on this?

**Comment by josecsotomorales** [comment]
@johnrengelman, I just wanted to say thanks for all the hard work on this, this plugin is a must-have in most of my Gradle projects 🚀

**Comment by oleg-nenashev** [comment]
I am ready to move forward on my side. Sorry for the long silence period; I was involved in getting the approvals for transfer and clarifying the process for mission-critical components. @Goooler we are ready to hand over permissions on the plugin portal to the previous plugin ID

**Comment by oleg-nenashev** [comment]
@Goooler FYI, I will be off for the next month, but somebody from the team might be able to help if you are still interested. @ljacomet can help with the permissions updates

FWIW, https://github.com/gradle/community/issues/15 is stuck pending internal approvals, and I do not have any ETA, so for now, the only actionable approach is @johnrengelman granting permissions as it was discussed before.

**Comment by oleg-nenashev** [comment]
So, for the transfer we need:

- [ ] @johnrengelman to add @Goooler as a collaborator
- [ ] Do the permission transfer. https://github.com/gradle/plugin-portal-requests is needed for that

**Comment by johnrengelman** [comment]
@Goooler what do you think? Should we create a new org, move the repo under that?
Do we want to keep using the same plugin id or start with a new one?

**Comment by Goooler** [comment]
A new org or @GradleUp, both look good to me.

**Comment by oleg-nenashev** [comment]
Both options LGTM at this stage. If the new org includes "Gradle" in it's name, I will take care of the trademark grant when I am black from vacation

**Comment by Goooler** [comment]
It's been placed at @GradleUp now.
