### ISSUE TITLE
Gradle Warning: CopyProcessingSpec.setFileMode(Integer) method has been deprecated

### ISSUE THREAD

**Issue by alexanderankin** [GradleUp/shadow#924]
including the plugin on gradle 8.8 results in the following message printed:

```
The CopyProcessingSpec.setFileMode(Integer) method has been deprecated. This is scheduled to be removed in Gradle 9.0. Please use the filePermissions(Action) method instead. Consult the upgrading guide for further information: https://docs.gradle.org/8.8/userguide/upgrading_version_8.html#unix_file_permissions_deprecated
```

### Shadow Version

`id 'com.github.johnrengelman.shadow' version '8.1.1'`

### Gradle Version

`distributionUrl=https\://services.gradle.org/distributions/gradle-8.8-bin.zip`

### Expected Behavior

no warning printed

### Actual Behavior

warning as described above

### Gradle Build Script(s)

do not believe it is relevant

### Content of Shadow JAR (`jar tf <jar file>` - post link to GIST if too long)

do not believe it is relevant

---

~~i plan to revisit this issue~~ but feel free to close if it is not useful (or welcome).

edit: turns out it is probably just this line of code:

https://github.com/johnrengelman/shadow/blob/9c5182d2d9c5f7141e4d2a525ec94d6111283cd9/src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowApplicationPlugin.groovy#L129

in this method:

https://github.com/johnrengelman/shadow/blob/9c5182d2d9c5f7141e4d2a525ec94d6111283cd9/src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowApplicationPlugin.groovy#L117-L134

called in the main apply method:

https://github.com/johnrengelman/shadow/blob/9c5182d2d9c5f7141e4d2a525ec94d6111283cd9/src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowApplicationPlugin.groovy#L30-L45

**Comment by Goooler** [comment]
See #876.
