### ISSUE TITLE
Documentation says `destinationDir` which has been changed for `destinationDirectory`

### ISSUE THREAD

**Issue by cyrhi** [GradleUp/shadow#925]
_Thank you for the plugin!_

Easy fix: [revert to](https://github.com/johnrengelman/shadow/blob/8.1.1/src/test/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowPluginSpec.groovy#L44) `destinationDir` or update [the documentation](https://github.com/johnrengelman/shadow/tree/8.1.1/src/docs/configuration#configuring-output-name) for `destinationDirectory`.
Not sure this change was worth breaking compatibility. I had to search the source code.

### Shadow Version
8.1.1

### Gradle Version
8.8

### Expected Behavior
`destinationDir` works.

### Actual Behavior
```
Could not set unknown property 'destinationDir' for task ':myProject:myTask' of type com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar.`
```

### Gradle Build Script(s)
```
task myTask(type: ShadowJar) {
    configurations = [project.configurations.myConfiguration]
    destinationDir = file("myFolder")
}
```

**Comment by Goooler** [comment]
Thanks for this report! Addressing the fix in #876.
