### ISSUE TITLE
Old shadow versions are unreachable

### ISSUE THREAD

**Issue by ofer-haim** [GradleUp/shadow#941]
Please check the [User Guide](http://imperceptiblethoughts.com/shadow) before submitting "how do I do 'x'?" questions!

### Shadow Version 
4.0.4

### Gradle Version
all

### Expected Behavior
I used to fetch shadow version from https://repo1.maven.org/maven2/com/github/jengelman/gradle/plugins/shadow/<VERSION>/shadow-<VERSION>.jar

I do see a different location, according to https://gradleup.com/shadow/changes/#v8-3-0, but it's only seems to be relevant for version 8.3.0:
https://repo.maven.apache.org/maven2/com/gradleup/shadow/shadow-gradle-plugin/

This was observed 3 days ago

<img width="1187" alt="image" src="https://github.com/user-attachments/assets/31dc79cd-6149-4d89-ab5c-7ae18bb4c884">

**Comment by ofer-haim** [comment]
https://gradleup.com/shadow/changes/#v8-3-0

**Comment by DaganAstur** [comment]
Same issue here for version 4.0.4, it suddenly stopped working and can't be found on maven's repo.

**Comment by Goooler** [comment]
https://plugins.gradle.org/plugin/com.github.johnrengelman.shadow

**Comment by DaganAstur** [comment]
For those having the issue, in this repo: https://plugins.gradle.org/m2/com/github/jengelman/gradle/plugins/shadow/4.0.4/ you can find the older versions disappeared from the other maven repos.
