### ISSUE TITLE
Plugin jar contains registration for missing Log4J annotation processor

### ISSUE THREAD

**Issue by marcphilipp** [GradleUp/shadow#965]
### Expected and Results

The [shadow-gradle-plugin-8.3.1.jar](https://plugins.gradle.org/m2/com/gradleup/shadow/shadow-gradle-plugin/8.3.1/shadow-gradle-plugin-8.3.1.jar) contains a `META-INF/services/javax.annotation.processing.Processor` file that contains a reference to `org.apache.logging.log4j.core.config.plugins.processor.PluginProcessor` but the annotation processor is not part of the JAR.

I strongly suspect the plugin jar should not contain a `META-INF/services/javax.annotation.processing.Processor` file at all.

### Related environent and versions

8.3.1

### Reproduction steps

This yields to problems when compiling Java classes with the plugin jar on the classpath and not using the `-proc:none` compiler arg.

**Comment by Goooler** [comment]
Thanks for the heads-up! This is due to https://github.com/GradleUp/shadow/pull/960#discussion_r1754555359.

**Comment by Goooler** [comment]
@marcphilipp Could you try out `8.3.2-SNAPSHOT`?

**Comment by marcphilipp** [comment]
The latest snapshot resolves the issue. Thanks for the quick turnaround! :+1:

**Comment by Goooler** [comment]
Thanks for your report!
