### ISSUE TITLE
BC in 8.3.2

### ISSUE THREAD

**Issue by skmedix** [GradleUp/shadow#977]
### Expected and Results

I expect to keep support for building on JDK 8, but shadow now requires JDK 11.

### Related environent and versions

Shadow 8.3.2
Gradle 8.10.1
JDK 8.0.422

### Anything else?

Since 8.3.2 shadow now uses jdependency 2.11, but since 2.11 jdependency now targets Java 11, resulting in java.lang.UnsupportedClassVersionError. This is a breaking change that wasn't listed in the changelog.

**Comment by Goooler** [comment]
Oooops, I forgot that. Done!
